<?php

namespace ContainerIJgERox;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThreads3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sQePedL.App\Entity\Threads' shared service.
     *
     * @return \App\Entity\Threads
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.sQePedL": it references class "App\\Entity\\Threads" but no such service exists.');
    }
}
