<?php

namespace ContainerHlBefaA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PkoNfOeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PkoNfOe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PkoNfOe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reply' => ['privates', '.errored..service_locator.PkoNfOe.App\\Entity\\Replies', NULL, 'Cannot autowire service ".service_locator.PkoNfOe": it references class "App\\Entity\\Replies" but no such service exists.'],
        ], [
            'reply' => 'App\\Entity\\Replies',
        ]);
    }
}
