eko_feed:
    hydrator: your_hydrator.custom.service # Optional, if you use entity hydrating with a custom hydrator
    translation_domain: test # Optional, if you want to use a custom translation domain
    feeds:
        article:
            title:       'My articles/posts'
            description: 'Latests articles'
            link:
                 route_name: acme_blog_main_index
                 route_params: {id: 2} # necessary if route contains required parameters
            encoding:    'utf-8'
            author:      'Vincent Composieux' # Only required for Atom feeds