<?php

namespace ContainerLOp0gLB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GBMNm5HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gBMNm5H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gBMNm5H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'topic' => ['privates', '.errored..service_locator.gBMNm5H.App\\Entity\\Topics', NULL, 'Cannot autowire service ".service_locator.gBMNm5H": it references class "App\\Entity\\Topics" but no such service exists.'],
        ], [
            'topic' => 'App\\Entity\\Topics',
        ]);
    }
}
