<?php

namespace ContainerLOp0gLB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BclwFzFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BclwFzF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BclwFzF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'rep' => ['privates', 'App\\Repository\\TopicsRepository', 'getTopicsRepositoryService', true],
            'threadsRepository' => ['privates', 'App\\Repository\\ThreadsRepository', 'getThreadsRepositoryService', true],
        ], [
            'doctrine' => '?',
            'rep' => 'App\\Repository\\TopicsRepository',
            'threadsRepository' => 'App\\Repository\\ThreadsRepository',
        ]);
    }
}
