<?php

namespace ContainerLOp0gLB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LuYAUBzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LuYAUBz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LuYAUBz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reply' => ['privates', '.errored..service_locator.LuYAUBz.App\\Entity\\Replies', NULL, 'Cannot autowire service ".service_locator.LuYAUBz": it references class "App\\Entity\\Replies" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'reply' => 'App\\Entity\\Replies',
        ]);
    }
}
