<?php

namespace ContainerLOp0gLB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FLTieuiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FLTieui' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FLTieui'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'thread' => ['privates', '.errored..service_locator.FLTieui.App\\Entity\\Threads', NULL, 'Cannot autowire service ".service_locator.FLTieui": it references class "App\\Entity\\Threads" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'thread' => 'App\\Entity\\Threads',
        ]);
    }
}
