<?php

namespace ContainerLOp0gLB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PzDelrDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pzDelrD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pzDelrD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'topic' => ['privates', '.errored..service_locator.pzDelrD.App\\Entity\\Topics', NULL, 'Cannot autowire service ".service_locator.pzDelrD": it references class "App\\Entity\\Topics" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'topic' => 'App\\Entity\\Topics',
        ]);
    }
}
