<?php

namespace ContainerLOp0gLB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReplies2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PkoNfOe.App\Entity\Replies' shared service.
     *
     * @return \App\Entity\Replies
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PkoNfOe": it references class "App\\Entity\\Replies" but no such service exists.');
    }
}
