<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userId', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userUsername', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userEmail', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userPassword', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userFirstname', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userLastname', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userBirthday', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userGender', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userPicture', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userPhonenumber', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userLevel', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userRole', '' . "\0" . 'App\\Entity\\User' . "\0" . 'threads'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userId', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userUsername', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userEmail', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userPassword', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userFirstname', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userLastname', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userBirthday', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userGender', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userPicture', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userPhonenumber', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userLevel', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userRole', '' . "\0" . 'App\\Entity\\User' . "\0" . 'threads'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUserId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getUserId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserUsername(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserUsername', []);

        return parent::getUserUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserUsername(string $userUsername): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserUsername', [$userUsername]);

        return parent::setUserUsername($userUsername);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserEmail', []);

        return parent::getUserEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserEmail(string $userEmail): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserEmail', [$userEmail]);

        return parent::setUserEmail($userEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPassword', []);

        return parent::getUserPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPassword(string $userPassword): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPassword', [$userPassword]);

        return parent::setUserPassword($userPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserFirstname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserFirstname', []);

        return parent::getUserFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserFirstname(string $userFirstname): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserFirstname', [$userFirstname]);

        return parent::setUserFirstname($userFirstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserLastname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserLastname', []);

        return parent::getUserLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserLastname(string $userLastname): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserLastname', [$userLastname]);

        return parent::setUserLastname($userLastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserBirthday(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserBirthday', []);

        return parent::getUserBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserBirthday(\DateTimeInterface $userBirthday): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserBirthday', [$userBirthday]);

        return parent::setUserBirthday($userBirthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserGender(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserGender', []);

        return parent::getUserGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserGender(string $userGender): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserGender', [$userGender]);

        return parent::setUserGender($userGender);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPicture(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPicture', []);

        return parent::getUserPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPicture(string $userPicture): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPicture', [$userPicture]);

        return parent::setUserPicture($userPicture);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPhonenumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPhonenumber', []);

        return parent::getUserPhonenumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPhonenumber(string $userPhonenumber): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPhonenumber', [$userPhonenumber]);

        return parent::setUserPhonenumber($userPhonenumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserLevel(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserLevel', []);

        return parent::getUserLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserLevel(int $userLevel): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserLevel', [$userLevel]);

        return parent::setUserLevel($userLevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserRole(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserRole', []);

        return parent::getUserRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserRole(string $userRole): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserRole', [$userRole]);

        return parent::setUserRole($userRole);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
