<?php

namespace ContainerMiiRY4H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_15ylnivService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.15ylniv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.15ylniv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::show' => ['privates', '.service_locator.EBzUzud', 'get_ServiceLocator_EBzUzudService', true],
            'App\\Controller\\ChartController::index' => ['privates', '.service_locator.l3e3tDC', 'get_ServiceLocator_L3e3tDCService', true],
            'App\\Controller\\PanierController::addToCart' => ['privates', '.service_locator.Niycchk', 'get_ServiceLocator_NiycchkService', true],
            'App\\Controller\\PanierController::deletePanier' => ['privates', '.service_locator.JJiO7pQ', 'get_ServiceLocator_JJiO7pQService', true],
            'App\\Controller\\PanierController::generatePanierPdf' => ['privates', '.service_locator.4Uag9kt', 'get_ServiceLocator_4Uag9ktService', true],
            'App\\Controller\\PanierController::panierStatistics' => ['privates', '.service_locator.tsnEguG', 'get_ServiceLocator_TsnEguGService', true],
            'App\\Controller\\PanierController::paniers' => ['privates', '.service_locator.tsnEguG', 'get_ServiceLocator_TsnEguGService', true],
            'App\\Controller\\PanierController::show' => ['privates', '.service_locator.aqSwrgC', 'get_ServiceLocator_AqSwrgCService', true],
            'App\\Controller\\ProductController::AddProduct' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProductController::UpdateProduct' => ['privates', '.service_locator.3DBU9FM', 'get_ServiceLocator_3DBU9FMService', true],
            'App\\Controller\\ProductController::deleteProduct' => ['privates', '.service_locator.3DBU9FM', 'get_ServiceLocator_3DBU9FMService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.7CJU70_', 'get_ServiceLocator_7CJU70Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AdminController:show' => ['privates', '.service_locator.EBzUzud', 'get_ServiceLocator_EBzUzudService', true],
            'App\\Controller\\ChartController:index' => ['privates', '.service_locator.l3e3tDC', 'get_ServiceLocator_L3e3tDCService', true],
            'App\\Controller\\PanierController:addToCart' => ['privates', '.service_locator.Niycchk', 'get_ServiceLocator_NiycchkService', true],
            'App\\Controller\\PanierController:deletePanier' => ['privates', '.service_locator.JJiO7pQ', 'get_ServiceLocator_JJiO7pQService', true],
            'App\\Controller\\PanierController:generatePanierPdf' => ['privates', '.service_locator.4Uag9kt', 'get_ServiceLocator_4Uag9ktService', true],
            'App\\Controller\\PanierController:panierStatistics' => ['privates', '.service_locator.tsnEguG', 'get_ServiceLocator_TsnEguGService', true],
            'App\\Controller\\PanierController:paniers' => ['privates', '.service_locator.tsnEguG', 'get_ServiceLocator_TsnEguGService', true],
            'App\\Controller\\PanierController:show' => ['privates', '.service_locator.aqSwrgC', 'get_ServiceLocator_AqSwrgCService', true],
            'App\\Controller\\ProductController:AddProduct' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProductController:UpdateProduct' => ['privates', '.service_locator.3DBU9FM', 'get_ServiceLocator_3DBU9FMService', true],
            'App\\Controller\\ProductController:deleteProduct' => ['privates', '.service_locator.3DBU9FM', 'get_ServiceLocator_3DBU9FMService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.7CJU70_', 'get_ServiceLocator_7CJU70Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AdminController::show' => '?',
            'App\\Controller\\ChartController::index' => '?',
            'App\\Controller\\PanierController::addToCart' => '?',
            'App\\Controller\\PanierController::deletePanier' => '?',
            'App\\Controller\\PanierController::generatePanierPdf' => '?',
            'App\\Controller\\PanierController::panierStatistics' => '?',
            'App\\Controller\\PanierController::paniers' => '?',
            'App\\Controller\\PanierController::show' => '?',
            'App\\Controller\\ProductController::AddProduct' => '?',
            'App\\Controller\\ProductController::UpdateProduct' => '?',
            'App\\Controller\\ProductController::deleteProduct' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:show' => '?',
            'App\\Controller\\ChartController:index' => '?',
            'App\\Controller\\PanierController:addToCart' => '?',
            'App\\Controller\\PanierController:deletePanier' => '?',
            'App\\Controller\\PanierController:generatePanierPdf' => '?',
            'App\\Controller\\PanierController:panierStatistics' => '?',
            'App\\Controller\\PanierController:paniers' => '?',
            'App\\Controller\\PanierController:show' => '?',
            'App\\Controller\\ProductController:AddProduct' => '?',
            'App\\Controller\\ProductController:UpdateProduct' => '?',
            'App\\Controller\\ProductController:deleteProduct' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
