<?php

namespace ContainerMiiRY4H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4Uag9ktService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4Uag9kt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4Uag9kt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'panier' => ['privates', 'App\\Entity\\Panier', 'getPanierService', true],
            'pdf' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
        ], [
            'panier' => 'App\\Entity\\Panier',
            'pdf' => 'App\\Service\\PdfService',
        ]);
    }
}
