<?php

namespace ContainerMiiRY4H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPanierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Panier' shared autowired service.
     *
     * @return \App\Entity\Panier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'Panier.php';

        return $container->privates['App\\Entity\\Panier'] = new \App\Entity\Panier();
    }
}
