<?php

namespace ContainerH1pOdm5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PquPSYiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pquPSYi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pquPSYi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'thread' => ['privates', '.errored..service_locator.pquPSYi.App\\Entity\\Threads', NULL, 'Cannot autowire service ".service_locator.pquPSYi": it references class "App\\Entity\\Threads" but no such service exists.'],
        ], [
            'thread' => 'App\\Entity\\Threads',
        ]);
    }
}
