<?php

namespace ContainerH1pOdm5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZAOy9XDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zAOy9XD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zAOy9XD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'threadsRepository' => ['privates', 'App\\Repository\\ThreadsRepository', 'getThreadsRepositoryService', true],
        ], [
            'threadsRepository' => 'App\\Repository\\ThreadsRepository',
        ]);
    }
}
