<?php

namespace ContainerEL9uiHr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FeL5bVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fe_l5bV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fe_l5bV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'topicsRepository' => ['privates', 'App\\Repository\\TopicsRepository', 'getTopicsRepositoryService', true],
        ], [
            'topicsRepository' => 'App\\Repository\\TopicsRepository',
        ]);
    }
}
