<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIJgERox\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIJgERox/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIJgERox.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIJgERox\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIJgERox\App_KernelDevDebugContainer([
    'container.build_hash' => 'IJgERox',
    'container.build_id' => 'bbad0d8d',
    'container.build_time' => 1713006278,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIJgERox');
